# Importing packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)
#linewidth - extend the no. of characters to fit in a single line of output as 100
#precision - set the number of decimal places to 2

# Importing file 

In [3]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ";", skip_header = 1, autostrip = True)
#autostrip - removes extra white spaces
#skip_header used since we saw that the entire first row had "nan" values
print(raw_data_np)

[[48010226.           nan    35000.   ...         nan         nan     9452.96]
 [57693261.           nan    30000.   ...         nan         nan     4679.7 ]
 [59432726.           nan    15000.   ...         nan         nan     1969.83]
 ...
 [50415990.           nan    10000.   ...         nan         nan     2185.64]
 [46154151.           nan         nan ...         nan         nan     3199.4 ]
 [66055249.           nan    10000.   ...         nan         nan      301.9 ]]


# Checking for incomplete data

In [4]:
np.isnan(raw_data_np).sum()

88005

In [5]:
temp_fill = np.nanmax(raw_data_np) + 1               # A filler for the missing entries which is the max of all values+1
temp_mean = np.nanmean(raw_data_np, axis = 0)        # Holds the mean for every column
# The warning means that some columns may be full of texts so mean connot be computed

C:\Users\Hp\AppData\Local\Temp\ipykernel_1464\2759050640.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis = 0)        # Holds the mean for every column


In [6]:
temp_mean
# The values having temp_mean as "nan" means either they were all strings in the column or all values were nan
# For computational purposes it is not advisable to put all strings and numbers in the same array, so we'll split them

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temp_stats = np.array([np.nanmin(raw_data_np, axis = 0), temp_mean, np.nanmax(raw_data_np, axis = 0)])
temp_stats

C:\Users\Hp\AppData\Local\Temp\ipykernel_1464\3317913290.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data_np, axis = 0), temp_mean, np.nanmax(raw_data_np, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Splitting the dataset

In [8]:
#We can differentiate between the string columns and numeric columns using the temp_mean
column_string = np.argwhere(np.isnan(temp_mean)).squeeze()
column_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
column_num = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Re-importing the dataset

In [10]:
# The string dataset
loan_data_string = np.genfromtxt("loan-data.csv", 
                                 delimiter = ";", 
                                 skip_header = 1, 
                                 autostrip = True, 
                                 usecols = column_string,
                                 dtype = np.str_)
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
# The numeric dataset
loan_data_num = np.genfromtxt("loan-data.csv", 
                               delimiter = ";", 
                               skip_header = 1, 
                               autostrip = True, 
                               usecols = column_num,
                               filling_values = temp_fill)
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

# The names of the columns

In [12]:
# We are interested only in the header of the original dataset
header_full = np.genfromtxt("loan-data.csv", delimiter = ";", autostrip = True, dtype = np.str_)[0,:]
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U69')

In [13]:
header_strings , header_nums = header_full[column_string] , header_full[column_num]

In [14]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [15]:
header_nums

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

# Creating Chechpoints

In [16]:
# Places throughout our code where we store a copy of our data (or parts of it)
# We can avoid the loss of a lot of progress
# It's a very healthy and reliable practice when working with large datasets and when cleaning various parts of it

In [17]:
def checkpoint(file_name , checkpoint_header , checkpoint_data):
    np.savez(file_name, header = checkpoint_header , data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [18]:
check = checkpoint("checkpoint-test", header_strings, loan_data_string)

In [19]:
check["header"]

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [20]:
check["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

# Manipulating text data : Issue Date

In [21]:
header_strings[0] = "Issue_Date"                   # Earlier issue_d was not so descriptive for its purpose
header_strings

array(['Issue_Date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [22]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [23]:
# The values are all from year 2015 so we can strip off -15 as it does not disrupt any useful information and store it
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0] , "-15")
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [24]:
# In analysis, represent month values as integers
# Store the data in lesser space
# Easy-to-follow order for months

In [25]:
months = np.array(["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])

In [26]:
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i],
                                     i,
                                     loan_data_string[:,0])
loan_data_string[:,0]
# These are string values for now but we'll not cast them right away (in a later stage)

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

# Loan Status

In [27]:
header_strings

array(['Issue_Date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [28]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [29]:
# In loan status, we can assign numbers to each status but in regression we are only considered if the candidate is in a 
# good financial condition
# So we'll categorize them as "good - 1" or "bad - 0"

In [30]:
status_bad = ["", "Charged Off", "Default", "Late (31-120 days)"]

In [31]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1], status_bad), 0, 1)

In [32]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

# Term

In [33]:
header_strings

array(['Issue_Date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [34]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [35]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2], " months")
loan_data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [36]:
header_strings[2] = "Term_months"         # More descriptive name

In [37]:
# We'll assign 60 for the missing value (because in CRM, we assume the worst)
loan_data_string[:,2] = np.where(loan_data_string[:,2] == "", '60', loan_data_string[:,2])
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

# Grade and Subgrade

In [38]:
header_strings

array(['Issue_Date', 'loan_status', 'Term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U69')

In [39]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [40]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

# Filling sub grade

In [41]:
# For filling sub grade, it is better to fill the worst(like B5, D5) for a corresponding grade
# np.unique(loan_data_string[:,3])[1:] - means we start the loop from position 1 in unique grade array, i.e., 'A' leaving ''
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i),
                                      i + '5',
                                      loan_data_string[:,4])

In [42]:
np.unique(loan_data_string[:,4], return_counts = True)
# We see there are 9 instances where grade and sub_grade, both have missing values

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [43]:
# So, for filling the empty spaces we are defining a new subgrade H1
loan_data_string[:,4] = np.where(loan_data_string[:,4] == '',
                                  'H1',
                                  loan_data_string[:,4])

In [44]:
np.unique(loan_data_string[:,4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

# Removing Grade

In [45]:
# Since the information about the grade can be found from subgrade, therefore it is redundant and can be deleted
loan_data_string = np.delete(loan_data_string, 3, axis = 1)

In [46]:
loan_data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [47]:
header_strings = np.delete(header_strings, 3)

In [48]:
header_strings[3]

'sub_grade'

# Converting subgrade

In [49]:
# We don't want to use np.where() everytime for accessing subgrades so we assign a value and convert it into a dictionary
key_subgrade = list(np.unique(loan_data_string[:,3]))
num_subgrade = list(range(1 , len(np.unique(loan_data_string[:,3])) + 1))
dict_subgrade = dict(zip(key_subgrade , num_subgrade))
dict_subgrade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [50]:
# Now we are replacing these values in the original data
for i in np.unique(loan_data_string[:,3]):
    loan_data_string[:,3] = np.where(loan_data_string[:,3] == i,
                                     dict_subgrade[i],
                                     loan_data_string[:,3])

In [51]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

# Verification status

In [52]:
header_strings

array(['Issue_Date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U69')

In [53]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [54]:
# '' & 'Not Verified' are considered bad = 0 amd the rest 2 are good = 1, so we replace them
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') | (loan_data_string[:,4] == 'Not Verified'), 0, 1)

In [55]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

# URL

In [56]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [57]:
loan_data_string[:,5] = np.chararray.strip(loan_data_string[:,5] , 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [58]:
loan_data_string[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [59]:
# Now the values of loan_id in the url is same as the id in the original header_full or header_nums
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U69')

In [60]:
loan_data_num[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [61]:
# Since the proved loan_id and id are the same, we can delete the url column because its value can be derived from 'id'
loan_data_string = np.delete(loan_data_string, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [62]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [63]:
header_strings

array(['Issue_Date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U69')

# State address

In [64]:
np.unique(loan_data_string[:,5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [65]:
header_strings[5] = "State_Address"

In [66]:
header_strings

array(['Issue_Date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status',
       'State_Address'], dtype='<U69')

In [67]:
# We assume that the empty values in loan_data_string[:,5] are left blank for the base region,i.e., Iowa in US 
# So we split these regions on the basis of regions coded as 0-Iowa, 1, 2, 3, 4, 5
loan_data_string[:,5] = np.where(loan_data_string[:,5] == '', 0, loan_data_string[:,5])
np.unique(loan_data_string[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [68]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [69]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), 4, loan_data_string[:,5])

In [70]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

# Converting to numbers

In [71]:
loan_data_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [72]:
loan_data_string = loan_data_string.astype(dtype = np.int32)
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

# Checkpoint 1 : For completing strings

In [73]:
checkpoint_strings = checkpoint("checkpoint-strings", header_strings, loan_data_string)

In [74]:
checkpoint_strings["header"]

array(['Issue_Date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status',
       'State_Address'], dtype='<U69')

In [75]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

# Manipulating Numeric Columns

In [76]:
header_nums

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

In [77]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [78]:
# Its a good practice to check for any nan values. However we have already substituted those values with temporary filler
np.isnan(loan_data_num).sum()

0

# ID

In [79]:
# The ID is a very crucial field and it should not contain any filler values and if it does we must substitute it with the 
# worst possible value
temp_fill

68616520.0

In [80]:
np.isin(loan_data_num[:,0], temp_fill)

array([False, False, False, ..., False, False, False])

In [81]:
np.isin(loan_data_num[:,0], temp_fill).sum()

0

# Temporary Stats

In [82]:
column_num

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [83]:
header_nums

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U69')

In [84]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [85]:
temp_stats[:,column_num]  # These are the nanmin, nanmean, nanmax of only the columns having numerical value

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [86]:
# Only for funded_amnt we will substitute filler values with the column's minimum and the rest with the column's maximum 

# Funded Amount

In [87]:
# So, we are replacing the filler values of funded_amnt (column=2 in loan_data_num) with min of that column
loan_data_num[:,2] = np.where(loan_data_num[:,2] == temp_fill,
                              temp_stats[0, column_num[2]], 
                              loan_data_num[:,2])
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

# Loan Amount, Interest Rate, Installment, Total payment

In [88]:
# Replacing with nanmax values
for i in [1,3,4,5]:
    loan_data_num[:,i] = np.where(loan_data_num[:,i] == temp_fill,
                                      temp_stats[2, column_num[i]],
                                      loan_data_num[:,i])
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

# Currency Change

# Exchange Rate

In [89]:
# These are the currency exchange rates for each month
eur_usd_sample = np.genfromtxt('EUR-USD.csv', delimiter = ',', autostrip = True, dtype = np.str_)
eur_usd_sample

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [90]:
# But for our conversions we'll choose the 'close' field
eur_usd = np.genfromtxt('EUR-USD.csv', delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [91]:
loan_data_string[:,0]           #These are the issue dates data (months converted to numbers)

array([ 5,  0,  9, ...,  6,  4, 12])

In [92]:
# Now, we are creating an array having the corresponding exchange_rate to the given month
# Where the month is zero, it is replaced by the mean of the eur_usd
exchange_rate = loan_data_string[:,0]

for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i , eur_usd[i-1] , exchange_rate)
    
exchange_rate = np.where(exchange_rate == 0 , np.mean(eur_usd) , exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [93]:
exchange_rate.shape

(10000,)

In [94]:
loan_data_num.shape

(10000, 6)

In [95]:
# We have to reshape because loan_data_num is 2D and exchange_rate is 1D so stacking will not be possible
exchange_rate = np.reshape(exchange_rate , (10000,1))

In [96]:
loan_data_num = np.hstack((loan_data_num, exchange_rate))
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [97]:
header_nums = np.concatenate((header_nums , np.array(['exchange_rate'])))
header_nums
# Thus we have successfully added a new field of exchange_rates for each month and its values

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U69')

# From USD to EUR

In [98]:
columns_dollar = np.array([1, 2, 4, 5])          
# Fields having values in dollar('loan_amnt', 'funded_amnt', 'installment', 'total_pymnt')

In [99]:
loan_data_num[:,6]            # Exchange_rate values

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [100]:
# Converting the USD to EUR by formula (USD / exchange_rate = EUR) and we are stacking(or adding) the converted fields to 
# the original array
for i in columns_dollar:
    loan_data_num = np.hstack((loan_data_num , np.reshape(loan_data_num[:,i] / loan_data_num[:,6] , (10000,1))))

In [101]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [102]:
loan_data_num.shape
# Earlier (10000, 6)
# Because + 'exchange_rate' + 4 dollar to eur converted fields

(10000, 11)

# Expanding the header

In [103]:
header_nums

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U69')

In [104]:
header_addition = np.array([column_name + '_EUR' for column_name in header_nums[columns_dollar]])
header_addition

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [105]:
header_nums = np.concatenate((header_nums , header_addition))
header_nums

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U69')

In [106]:
# We are adding _USD to dollar columns to be more descriptive 
header_nums[columns_dollar] = np.array([column_name + '_USD' for column_name in header_nums[columns_dollar]])

In [107]:
header_nums

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U69')

In [108]:
# Now we are rearranging the columns so that USD columns are followed by their corresponding EUR columns
columns_index_order = [0, 1, 7, 2, 8, 3, 4, 9, 5, 10, 6]
header_nums = header_nums[columns_index_order]
header_nums

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U69')

In [109]:
loan_data_num = loan_data_num[:,columns_index_order]
loan_data_num

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

# Interest Rate

In [110]:
header_nums[5]

'int_rate'

In [111]:
loan_data_num[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [112]:
# Transform the interest rates to percentage values between 0 and 1
loan_data_num[:,5] = loan_data_num[:,5] / 100
loan_data_num[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

# Checkpoint 2: Numeric

In [113]:
checkpoint_num = checkpoint("Checkpoint-Numeric", header_nums, loan_data_num)

In [114]:
checkpoint_num["header"], checkpoint_num["data"]

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U69'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

# Creating the "Complete" Dataset

In [115]:
checkpoint_strings['data'].shape

(10000, 6)

In [116]:
checkpoint_num["data"].shape

(10000, 11)

In [117]:
loan_data = np.hstack((checkpoint_num["data"] , checkpoint_strings['data']))
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [118]:
loan_data.shape

(10000, 17)

In [119]:
np.isnan(loan_data).sum()

0

In [120]:
header_full = np.concatenate((checkpoint_num["header"] , checkpoint_strings["header"]))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'Issue_Date', 'loan_status', 'Term_months', 'sub_grade', 'verification_status',
       'State_Address'], dtype='<U69')

# Sorting the new dataset

In [121]:
# We will sort the complete dataset according to the first column id
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [122]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [123]:
# Checking if the id index is sorted
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

# Storing the new dataset

In [124]:
my_loan_data = np.vstack((header_full , loan_data))
my_loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'State_Address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U69')

In [125]:
np.savetxt("loan-data-preprocessed.csv" , my_loan_data , fmt = "%s" , delimiter = ',')